name: rescan-codescan-sarif-manual

on: workflow_dispatch

jobs:
  wait_for:
    name: Wait for any issues, gh-int + code_scanning_alerts on
    runs-on: ubuntu-latest
    container: node:16
    permissions:
      id-token: write
    steps:
      - name: Scan Start
        id: start
        uses: NeuraLegion/run-scan@release
        with:
          api_token: ${{ secrets.BRIGHT_TOKEN}}
          hostname: app.brightsec.com
          name: Bright Scan - ${{ github.sha }}
          restart_scan: ${{ secrets.BRIGHT_SCANIDMULT}}
      - name: Wait for breakpoint
        id: wait
        uses: NeuraLegion/wait-for@release
        with:
          api_token:  ${{ secrets.BRIGHT_TOKEN }}
          hostname: app.brightsec.com
          scan: ${{ steps.start.outputs.id }}
          wait_for: high
          code_scanning_alerts: false
          github_token: ${{ secrets.KEY_GITHUB }}
          timeout: 600
      - name: Upload SARIF file - No GHAS
        uses: actions/upload-artifact@v4
        with: 
          name: BrightSecurity_Report_${{ github.run_id }}
          path: bright.sarif
      - name: Upload results to MSDO
        uses: microsoft/security-devops-action@v1
        id: msdo
        with:
          existingFilename: bright.sarif
